import type { FunctionCallRendererConfig } from './types';

/**
 * Default configuration for function call parsing and rendering
 */
export const CONFIG: FunctionCallRendererConfig = {
  knownLanguages: [
    'javascript',
    'typescript',
    'python',
    'java',
    'cpp',
    'csharp',
    'c',
    'rust',
    'go',
    'ruby',
    'php',
    'swift',
    'kotlin',
    'scala',
    'bash',
    'shell',
    'sh',
    'html',
    'xml',
    'css',
    'sql',
    'json',
    'jsonl',
    'yaml',
    'yml',
    'toml',
    'ini',
    'markdown',
    'md',
    'perl',
    'lua',
    'r',
    'text',
  ],
  handleLanguageTags: true,
  maxLinesAfterLangTag: 3,
  enableDirectMonitoring: true,
  streamingContainerSelectors: ['pre', 'code'],
  updateThrottle: 100,
  streamingMonitoringInterval: 500,
  largeContentThreshold: 10000,
  maxContentPreviewLength: 200,
  debug: false,
};
